#!/bin/bash
sudo mkdir -p /var/lib/vz/snippets
cat << EOF | sudo tee /var/lib/vz/snippets/k3s-node.yaml
#cloud-config
runcmd:
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install -y qemu-guest-agent
    - systemctl start qemu-guest-agent
    - systemctl disable multipathd.socket
    - systemctl disable multipath-tools.service
    - reboot
EOF
